# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\"\x07\n\x05\x45mpty\"7\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"N\n\x0cTaskResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"/\n\x10ListTasksRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"6\n\x11ListTasksResponse\x12!\n\x05tasks\x18\x01 \x03(\x0b\x32\x12.task.TaskResponse\"1\n\x13UpdateStatusRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x8b\x01\n\rStatsResponse\x12\x13\n\x0btotal_tasks\x18\x01 \x01(\x05\x12\x34\n\tby_status\x18\x02 \x03(\x0b\x32!.task.StatsResponse.ByStatusEntry\x1a/\n\rByStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\xf3\x01\n\x0bTaskService\x12\x39\n\nCreateTask\x12\x17.task.CreateTaskRequest\x1a\x12.task.TaskResponse\x12<\n\tListTasks\x12\x16.task.ListTasksRequest\x1a\x17.task.ListTasksResponse\x12=\n\x0cUpdateStatus\x12\x19.task.UpdateStatusRequest\x1a\x12.task.TaskResponse\x12,\n\x08GetStats\x12\x0b.task.Empty\x1a\x13.task.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATSRESPONSE_BYSTATUSENTRY']._loaded_options = None
  _globals['_STATSRESPONSE_BYSTATUSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_CREATETASKREQUEST']._serialized_start=29
  _globals['_CREATETASKREQUEST']._serialized_end=84
  _globals['_TASKRESPONSE']._serialized_start=86
  _globals['_TASKRESPONSE']._serialized_end=164
  _globals['_LISTTASKSREQUEST']._serialized_start=166
  _globals['_LISTTASKSREQUEST']._serialized_end=213
  _globals['_LISTTASKSRESPONSE']._serialized_start=215
  _globals['_LISTTASKSRESPONSE']._serialized_end=269
  _globals['_UPDATESTATUSREQUEST']._serialized_start=271
  _globals['_UPDATESTATUSREQUEST']._serialized_end=320
  _globals['_STATSRESPONSE']._serialized_start=323
  _globals['_STATSRESPONSE']._serialized_end=462
  _globals['_STATSRESPONSE_BYSTATUSENTRY']._serialized_start=415
  _globals['_STATSRESPONSE_BYSTATUSENTRY']._serialized_end=462
  _globals['_TASKSERVICE']._serialized_start=465
  _globals['_TASKSERVICE']._serialized_end=708
# @@protoc_insertion_point(module_scope)
